services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rinha

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - mongodb
      - redis
volumes:
  mongodb_data:
  redis_data:
