services:
  mongodb:
    image: mongo:6.0
    networks:
      - payment-processor
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - payment-processor

  backend1:
    build: .
    image: calixtoneto/rinha-backend-2025:latest
    depends_on:
      - mongodb
      - redis
    expose:
      - "9999"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  backend2:
    build: .
    image: calixtoneto/rinha-backend-2025:latest
    depends_on:
      - mongodb
      - redis
    expose:
      - "9999"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  nginx:
    image: nginx:latest
    depends_on:
      - backend1
      - backend2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

networks:
  payment-processor:
    driver: bridge

volumes:
  mongo-data:
