spring:
  application:
    name: rinha-backend-2025
  data:
    mongodb:
      uri: mongodb://mongodb:27017/rinha
      database: rinha
    redis:
      host: redis
      port: 6379
resilience4j:
  circuitbreaker:
    instances:
      paymentProcessor:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      paymentProcessor:
        maxAttempts: 3
        waitDuration: 100ms
server:
  port: 9999
payment:
  processor:
    default:
      url: http://payment-processor-default:8080
    fallback:
      url: http://payment-processor-fallback:8080
logging:
  level:
    org.springframework: DEBUG
